# Generated by Django 4.1.7 on 2023-04-16 16:52

from django.db import migrations
import phone_field.models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_alter_profile_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="phone",
            field=phone_field.models.PhoneField(
                blank=True, help_text="Contact phone number", max_length=31
            ),
        ),
    ]
