# Generated by Django 4.1.7 on 2023-03-04 21:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0002_segmenttype_segment"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="segment",
            name="description",
        ),
        migrations.RemoveField(
            model_name="segment",
            name="title",
        ),
        migrations.AddField(
            model_name="segment",
            name="sequence",
            field=models.IntegerField(default=0, verbose_name="Sequence"),
        ),
        migrations.AddField(
            model_name="segment",
            name="variables",
            field=models.TextField(default="{}", verbose_name="Variables"),
        ),
        migrations.AddField(
            model_name="segmenttype",
            name="template",
            field=models.TextField(default="", verbose_name="Template"),
        ),
        migrations.AddField(
            model_name="segmenttype",
            name="variables",
            field=models.TextField(default="{}", verbose_name="Variables"),
        ),
    ]
