# Generated by Django 4.1.7 on 2023-03-24 23:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0003_remove_segment_description_remove_segment_title_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="description",
            field=models.TextField(default="", verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="service",
            name="topic",
            field=models.CharField(max_length=200, verbose_name="Title"),
        ),
    ]
