# Generated by Django 4.1.7 on 2023-04-02 21:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0004_service_description_alter_service_topic"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScriptElements",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("liturgist_name", models.CharField(max_length=100)),
                ("prelude_hymn_number", models.IntegerField()),
                ("prelude_hymn_name", models.CharField(max_length=100)),
                ("opening_words", models.TextField()),
                ("principle_or_source_number", models.IntegerField()),
                ("principle_or_source", models.CharField(max_length=100)),
                ("principle_or_source_text", models.TextField()),
                ("first_hymn_number", models.IntegerField()),
                ("first_hymn_name", models.CharField(max_length=100)),
                ("meditation_reading", models.TextField()),
                ("metta_singer", models.CharField(max_length=100)),
                ("second_hymn_number", models.IntegerField()),
                ("second_hymn_name", models.CharField(max_length=100)),
                ("readers_names", models.CharField(max_length=100)),
                ("singers_names", models.CharField(max_length=100)),
                ("zoom_host_name", models.CharField(max_length=100)),
                ("slide_manager_name", models.CharField(max_length=100)),
                ("shared_plate_partner", models.CharField(max_length=100)),
                ("final_hymn_number", models.IntegerField()),
                ("final_hymn_name", models.CharField(max_length=100)),
                ("circle_round_singer", models.CharField(max_length=100)),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="services.service",
                    ),
                ),
            ],
        ),
    ]
