# Generated by Django 4.1.7 on 2023-04-02 23:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0005_scriptelements"),
    ]

    operations = [
        migrations.CreateModel(
            name="Speaker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="Name")),
                ("biography", models.TextField(verbose_name="Biography")),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_modified", models.DateTimeField(auto_now=True)),
            ],
        ),
        # migrations.AlterField(
        #     model_name="service",
        #     name="speaker",
        #     field=models.ForeignKey(
        #         on_delete=django.db.models.deletion.CASCADE, to="services.speaker"
        #     ),
        # ),
    ]
