# Generated by Django 4.1.7 on 2023-04-03 20:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0006_speaker_alter_service_speaker"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="speaker",
            field=models.CharField(max_length=50, verbose_name="Speaker"),
        ),
    ]
