# Generated by Django 4.1.7 on 2023-04-13 23:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0009_delete_segment_delete_segmenttype"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="service",
            options={"ordering": ["-service_date"]},
        ),
        migrations.AddField(
            model_name="scriptelements",
            name="date_created",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="scriptelements",
            name="date_modified",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="speaker",
            name="email",
            field=models.EmailField(
                default="admin@bfuu-wsc.org", max_length=254, verbose_name="Email"
            ),
            preserve_default=False,
        ),
    ]
