# Generated by Django 4.1.7 on 2023-04-14 18:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0010_alter_service_options_scriptelements_date_created_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="speaker",
            name="biography",
            field=models.TextField(default="", verbose_name="Biography"),
        ),
        migrations.AlterField(
            model_name="speaker",
            name="email",
            field=models.EmailField(
                blank=True, max_length=254, null=True, verbose_name="Email"
            ),
        ),
    ]
