# Generated by Django 4.1.7 on 2023-04-16 16:52

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0011_alter_speaker_biography_alter_speaker_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="in_person_attendance",
            field=models.IntegerField(default=0, verbose_name="In Person Attendance"),
        ),
        migrations.AddField(
            model_name="service",
            name="offering",
            field=models.DecimalField(
                decimal_places=2, default=0.0, max_digits=10, verbose_name="Offering"
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="zoom_attendance",
            field=models.IntegerField(default=0, verbose_name="Zoom Attendance"),
        ),
        migrations.AddField(
            model_name="speaker",
            name="phone",
            field=phone_field.models.PhoneField(
                blank=True, max_length=31, null=True, verbose_name="Phone"
            ),
        ),
    ]
