# Generated by Django 4.1.7 on 2023-03-17 20:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Hymn",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("number", models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name="Verse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("verse_number", models.IntegerField()),
                ("verse", models.TextField()),
                (
                    "hymn",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="hymnal.hymn"
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="verse",
            index=models.Index(
                fields=["hymn", "verse_number"], name="hymn_verse_number_idx"
            ),
        ),
    ]
